### ISSUE TITLE
Circle arcs not smooth when points very near one another

### ISSUE THREAD

**Issue by ctrlcctrlv** [MFEK/math.rlib#27]
cc @simoncozens @RosaWagner this is the correct issue for the discussion had at the tail end of the resolved #16.

**Comment by ctrlcctrlv** [comment]
I already have a theory. I think it's a bad merger. Note how the two kinks are being caused by two times colocated corner points:

![image](https://user-images.githubusercontent.com/838783/164278522-1aa4dd8f-d3b7-4c76-8b00-18bcc86816f5.png)

But we should rightly expect that every point on the segment which links a cap or join should be a curve point with two non-colocated handles, and that the first and last points should only be one time colocated.

**Comment by ctrlcctrlv** [comment]
It's almost certainly a merger problem.

Everything looks fine on my end pre-merger.

![image](https://user-images.githubusercontent.com/838783/164351134-f7cdafc1-57ac-4f39-984e-09738eaa51ba.png)

![image](https://user-images.githubusercontent.com/838783/164351153-96c3c3fd-dfb0-4e53-98cc-8fc96c57fc28.png)

How are you merging @simoncozens @rosawagner?

If you don't see this before the segmentwise merger—what do you see?

**Comment by ctrlcctrlv** [comment]
Okay. Here's what we're doing administratively.

This issue is getting closed because `--segmentwise` was a hack which I thought would be fine, but circular arcs are not perfectly representable as cubic Bezier curves.

So, _any overlap merge_ would struggle with these two overlapping Bézier curves which are almost—yet not quite—equivalent.

Issue #16—not #17—is getting _reopened_ because segmentwise is not an appropriate fix.

I will then try to fix once again the path builder method of creating stroke outlines.

Thanks for user patience.

**Comment by davelab6** [comment]
![Screenshot_20220421-201802](https://user-images.githubusercontent.com/261579/164583448-9c67aa0d-2a67-441d-b315-3300348e4207.png)

The control points angled down (red) seem bad to me. I'm expecting a smooth top (green). Maybe unreasonably, if the underlying strokes don't have co-positioned top points.

**Comment by ctrlcctrlv** [comment]
@davelab6 they aren't. they are part of different paths.

For clarity see this exploded version:

![image](https://user-images.githubusercontent.com/838783/164584830-26dab077-091f-48cc-a0f7-645d63f8f44c.png)

**Comment by davelab6** [comment]
Ah good call. I see the "4th segment of the beach ball" now.

![Uploading Screenshot_20220421-204510.png…]()

**Comment by davelab6** [comment]
Ah good call. I see the "4th segment of the beach ball" now. 

![Screenshot_20220421-204510](https://user-images.githubusercontent.com/261579/164586275-d3c5d9c5-c297-4446-81ab-2712b7c9ac3c.png)
